apiVersion: v1
kind: Secret
metadata:
  name: smart-contract-lifecycle-mgr-api-db-credentials
  labels:
    app: {{ .Values.fullnameOverride }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  name: {{ .Values.postgres.name | b64enc }}