apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: app
    port: {{ .Values.service.extAppPort }}
    targetPort: {{ .Values.service.appPort }}
    protocol: TCP
  - name: http
    port: {{ .Values.service.appPort }}
    protocol: TCP
    targetPort: {{ .Values.service.appPort }}
  selector:
    app: {{ include "smart-contract-lifecycle-mgr-api.fullname" . }}