{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smart-contract-lifecycle-mgr-api.serviceAccountName" . }}
  labels:
{{ include "smart-contract-lifecycle-mgr-api.labels" . | nindent 4 }}
{{- end -}}
