server:
  port: ${SERVER_PORT:8087}

dlt:
  driver: corda

corda:
  rpc:
    host: ${CORDA_RPC_HOST:localhost}
    rpcPort: ${CORDA_RPC_PORT:10006}
    username: ${CORDA_RPC_USERNAME:user1}
    password: ${CORDA_RPC_PASSWORD:test}

  governanceNodeNames: # Corda X500 names of valid governance nodes
    - "O=GovernanceNode,L=Madrid,C=ES"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true

spring:
  application:
    name: smart-contract-lifecycle-manager
  h2:
    console:
      enabled: true
  database: h2
  console: true
  path: /h2
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    enabled: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

datasource:
  platform: h2
  url: jdbc:h2://localhost:${server.port}/h2
  username: sa
  password: 1234
  driverClassName: org.h2.Driver
