name: Generate OpenAPI docs

on:
  pull_request:
    branches:
      - master

jobs:
  openapi-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate openapi.yaml
        run: ./gradlew clean generateOpenApiDocs
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets._5GZORRO_PAF }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: 'docs/swagger-ui'
          message: 'Github Action: update OpenAPI YAML commit'
          push: true
