name: Publish CordApps And API to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Publish package
        run: ./gradlew -Pversion=${{ env.RELEASE_VERSION }} publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets._5GZORRO_PAF }}
      - name: Publish Spring API
        run: ./gradlew -Pversion=${{ env.RELEASE_VERSION }} jib -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
